python -u train.py Chinatown UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py SonyAIBORobotSurface1 UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py ItalyPowerDemand UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py MoteStrain UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py SonyAIBORobotSurface2 UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py TwoLeadECG UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py SmoothSubspace UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py ECGFiveDays UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Fungi UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py CBF UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py BME UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py UMD UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py DiatomSizeReduction UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py DodgerLoopWeekend UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py DodgerLoopGame UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py GunPoint UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Coffee UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py FaceFour UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py FreezerSmallTrain UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py ArrowHead UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py ECG200 UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Symbols UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py ShapeletSim UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py InsectEPGSmallTrain UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py BeetleFly UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py BirdChicken UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py ToeSegmentation1 UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py ToeSegmentation2 UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Wine UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Beef UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Plane UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py OliveOil UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py SyntheticControl UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py PickupGestureWiimoteZ UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py ShakeGestureWiimoteZ UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py GunPointMaleVersusFemale UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py GunPointAgeSpan UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py GunPointOldVersusYoung UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Lightning7 UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py DodgerLoopDay UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py PowerCons UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py FacesUCR UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Meat UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Trace UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py MelbournePedestrian UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py MiddlePhalanxTW UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py DistalPhalanxOutlineAgeGroup UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py MiddlePhalanxOutlineAgeGroup UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py ProximalPhalanxTW UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py ProximalPhalanxOutlineAgeGroup UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py DistalPhalanxTW UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Herring UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Car UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py InsectEPGRegularTrain UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py MedicalImages UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Lightning2 UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py FreezerRegularTrain UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Ham UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py MiddlePhalanxOutlineCorrect UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py DistalPhalanxOutlineCorrect UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py ProximalPhalanxOutlineCorrect UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Mallat UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py InsectWingbeatSound UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Rock UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py GesturePebbleZ1 UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py SwedishLeaf UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py CinCECGTorso UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py GesturePebbleZ2 UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Adiac UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py ECG5000 UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py WordSynonyms UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py FaceAll UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py GestureMidAirD2 UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py GestureMidAirD3 UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py GestureMidAirD1 UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py ChlorineConcentration UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py HouseTwenty UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Fish UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py OSULeaf UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py MixedShapesSmallTrain UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py CricketZ UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py CricketX UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py CricketY UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py FiftyWords UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Yoga UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py TwoPatterns UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py PhalangesOutlinesCorrect UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Strawberry UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py ACSF1 UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py AllGestureWiimoteY UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py AllGestureWiimoteX UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py AllGestureWiimoteZ UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Wafer UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py WormsTwoClass UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Worms UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Earthquakes UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Haptics UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Computers UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py InlineSkate UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py PigArtPressure UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py PigCVP UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py PigAirwayPressure UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Phoneme UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py ScreenType UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py LargeKitchenAppliances UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py SmallKitchenAppliances UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py RefrigerationDevices UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py UWaveGestureLibraryZ UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py UWaveGestureLibraryY UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py UWaveGestureLibraryX UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py ShapesAll UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Crop UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py SemgHandGenderCh2 UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py EOGVerticalSignal UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py EOGHorizontalSignal UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py MixedShapesRegularTrain UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py SemgHandMovementCh2 UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py SemgHandSubjectCh2 UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py PLAID UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py UWaveGestureLibraryAll UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py ElectricDevices UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py EthanolLevel UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py StarLightCurves UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py NonInvasiveFetalECGThorax1 UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py NonInvasiveFetalECGThorax2 UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py FordA UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py FordB UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py HandOutlines UCR --archive UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
