python -u train.py ERing UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Libras UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py AtrialFibrillation UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py BasicMotions UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py RacketSports UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Handwriting UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Epilepsy UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py JapaneseVowels UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py UWaveGestureLibrary UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py PenDigits UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py StandWalkJump UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py NATOPS UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py ArticularyWordRecognition UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py FingerMovements UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py LSST UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py HandMovementDirection UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Cricket UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py CharacterTrajectories UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py EthanolConcentration UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py SelfRegulationSCP1 UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py SelfRegulationSCP2 UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py Heartbeat UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py PhonemeSpectra UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py SpokenArabicDigits UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py EigenWorms UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py DuckDuckGeese UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py PEMS-SF UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py FaceDetection UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py MotorImagery UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u train.py InsectWingbeat UEA --archive UEA --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
